---
services:
  humanitz:
    image: indifferentbroccoli/humanitz-server-docker
    platform: linux/amd64
    restart: unless-stopped
    container_name: humanitz
    stop_grace_period: 30s
    ports:
      - 7777:7777/udp
      - 27015:27015/udp
      - 8888:8888/tcp
    env_file:
      - .env
    volumes:
      - ./server-files:/home/steam/server-files
